---
  - name: Install libselinux-python
    yum:
      name: libselinux-python
      state: latest

  - name: Install libsemanage-python
    yum:
      name: libsemanage-python
      state: latest

  - name: Enable httpd network connect for selinux
    seboolean:
      name: httpd_can_network_connect_db
      state: yes
      persistent: yes

